- .github/workflows/ruby.yml
Some blog articles have embedded Ruby code.
Run them when opening pull requests.
> .github: add workflow for Ruby tests

- go.mod
- go.sum
- main.go
I want to provide auto-heading links.
I was using an old version of blackfriday.
Its documentation is confusing due to its v1 to v2 migration.
gomarkdown is now the top result on Google for Go Markdown parsing.
It took less than 5 minutes to read and implement.
https://github.com/gomarkdown/markdown
> main.go: switch from blackfriday to gomarkdown

- main.go
If an article's date is in the future,
publish it during `blog serve` but
don't publish it during `blog build`.
> main.go: schedule articles

- articles/pull-requests-and-kanban.md
At Chain, Interstellar, and Pogo,
we had a program called `slashland` that enforced this.
This GitHub action is a cheaper, faster way to set up
similar functionality.
> articles/pull-requests-and-kanban: document autosquash

- articles/update-a-github-fork.md
The `upstream` remote is now added automatically:
https://github.com/cli/cli/releases/tag/v0.6.3
> articles/update-a-github-fork: remove now-automated step

- theme/public/robots.txt
This functionally the same as having no robots.txt file.
But, it removes the top "resource not found" item in Netlify Analytics.
https://docs.netlify.com/monitor-sites/analytics/
> theme: add robots.txt

- articles/thin-api-clients.md
- code/slack_webhook.rb
- code/slackwebhook.go
- code/stripe-card-token.ts
- config.json
Provide Ruby, Go, and TypeScript examples.
> articles/thin-api-clients: add

- articles/asdf-version-manager.md
I install Go differently.
Also, update to more modern version numbers,
make sure they're the same.
> articles: remove Go from ASDF article

- articles/asdf-version-manager.md
I'm not directly using it much.
Not sure it's the best way to install python.
> articles: remove Python from ASDF article

- main.go
After feed.json, the other 404s are all /archive requests.
Probably bots, but make it easier to read the analytics.
> main.go: redirect /archive/* links to /

- main.go
Print line of `check` caller that causes crash.
Fix `unlinkat directory not empty` error.
> main.go: fix crashes

- .gitignore
- articles/cache-api-requests.md
- code/cache-api-requests/main.rb
- code/cache-api-requests/schema.sql
- config.json
I've been writing most programs lately with fewer dependencies,
no ORMs, only a Postgres driver in the language used by the project.
This older article was starting to feel out of date.
Update it with the style I'd use to re-write the same program today.
> articles: rewrite Cache API Requests in current style

- articles/deno.md
I was seeing issues with the Homebrew install for Deno.
Install it directly instead.
Also, add `$PATH` information.
> articles/deno: adjust install instructions

- articles/format-sql-in-vim.md
- articles/postgres-set-variable.md
- articles/run-sql-from-vim.md
- config.json
This summer,
I wrote two quick tips on dev.to
about using Postgres from Vim:
https://dev.to/croaky/format-sql-on-save-run-sql-with-leader-r-296d
https://dev.to/croaky/postgres-set-variable-21ld
I would like to move them to my canonical blog.
Re-reading them, I realized they should be split into three articles.
Backdate as appropriate.
> all: extract dev.to articles

- config.json
> config.json: don't punctuate article descriptions

- theme/article.html
- theme/index.html
- theme/public/_headers
Add `width` and `height` attributes to logo `img` tag.
https://web.dev/optimize-cls/#images-without-dimensions
Add `rel="noopener"` attribute for external anchors.
https://web.dev/external-anchors-use-rel-noopener/
Add `connect-src: 'self';` to CSP rules so Lighthouse can get robots.txt
https://github.com/nhoizey/nicolas-hoizey.com/commit/6b10c62bb897c8bd7ac425c823a9adfbe9766c32
> theme: fix low-hanging Lighthouse audit items

- README.md
- config.json
- go.mod
- go.sum
- main.go
- theme/article.html
- theme/index.html
I'm removing the JSON feed because:
* I don't use a feed reader.
So, it's difficult to test whether anything is funky with it.
* The code is simpler.
* I treat the site more like a wiki than a blog.
Maybe the project name should change?
I don't know if people are using the feed but
if anyone wants to follow along,
I've started a [newsletter](https://dancroak.substack.com/)
and added a button linking to it in the footer.
> all: remove JSON feed

- articles/heroku-postgres-read-replica-with-rails.md
I don't think you can use the HA as a read replica:
https://devcenter.heroku.com/articles/heroku-postgres-ha
> articles/read-replica: remove HA section

- theme/article.html
- theme/index.html
I believe the `font-variation-settings: normal` lines
are now less needed as they were put in place for
a Chrome 81 font bolding bug.
Move dark mode media query to end.
Fall back to purple for article page h1 on non-WebKit browsers.
> theme: remove less-needed CSS

- articles/mystery-guests-in-tests.md
- config.json
- theme/article.html
Keep the page cleaner, only one CTA in footer: back to index.
> theme/article: remove newsletter CTA in footer

- articles/ssh-ed25519.md
- config.json
`ssh-add -K` has been replaced by `ssh-add --apple-use-keychain`.
Include copy-paste into GitHub to finish off process.
> articles/ssh-ed25519: update flag

- articles/run-sql-in-vim.md
Previously, I would see output containing the sequence `^[[H^[[2J`,
an ANSI escape code for clearing the screen. In many terminals:
- `^[[H` moves the cursor to the home position (i.e., the top-left of
the screen).
- `^[[2J` clears the screen from the cursor to the end of the screen.
When I ran the `clear` command, it sends these escape sequences to the
terminal to clear the screen. However, when I run the command from
within Vim using `:!`, Vim captures and displays the output of the
command, including the escape sequences, which don't get interpreted but
rather get shown as is.
To avoid seeing the escape sequences, replace the `clear` command with
another approach. One way to achieve this without the escape sequences
being printed is by using Vim's built-in command to clear the screen: …
> articles/run-sql-in-vim: use :redraw! instead of clear

- code/postgres/db-download-prod.sh
- code/postgres/db-restore-dev.sh
- Use parallel processing to improve speed.
- Use `--role application` flags with `cb uri`
This is necessary for avoiding permissions errors.
> code/postgres: use parallel processing

- articles/cmd/mdembed.md
- theme/index.html
Write about the `mdembed` program for embedding code files in Markdown,
which I wrote to enhance my "LLM in Vim" workflow.
> articles/cmd/mdembed: add

- theme/css/site.css
- Replace rigid 55% width rules with responsive max-width approach
- Add intermediate breakpoints for tablets (768-1024px) and medium screens (1025-1199px)
- Improve content width scaling: 38rem base → 45rem tablets → 50rem medium → 55rem desktop
- Adjust sidenote positioning for each breakpoint to maintain proper layout
- Preserve mobile sidenote toggle behavior (<760px)
- Format CSS with prettier
Fixes the narrow content issue on smaller viewports while maintaining
full Tufte CSS sidenote compatibility across all screen sizes.
> theme: use max-width + breakpoints for better mobile readability
