croaky/blog

README.md
config.json
main.go

Now that the `blog` key is gone, the JSON can be an array.

main.go: flatten config.json structure

---

theme/article.html
theme/index.html
theme/public/_headers

Cursor pointer, `h2`'s only, no link graphic.

theme: add lightweight "jump to heading IDs"

---

.github/workflows/daily.yml
.github/workflows/ruby.yml
README.md

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow
https://docs.netlify.com/configure-builds/build-hooks/

.github/workflows/daily: re-build for scheduled articles

---

README.md
articles/schedule-netlify-builds-with-github-actions.md
config.json
main.go
theme/article.html
theme/index.html

This article is the first live test
of an article scheduled in the future.
It also writes about how it works: meta!

articles/schedule-netlify-builds-with-github-actions: add

---

articles/ssh-ed25519.md
config.json

Name-check @ryandotsmith 👋.
Play with adding emoji into articles.

articles/ssh-ed25519: copy edits

---

theme/article.html
theme/index.html

Provide back link on articles.

theme: touch-up header and footer

---

config.json
main.go
theme/article.html
theme/index.html
theme/public/_headers

Toggling tags should always have a year for each group.

theme/index: group articles by year, show description

---

theme/article.html
theme/index.html

Make logo clickable from index for consistency with article page.
Make images in articles less intense in dark mode.

theme: adjust images and logo

---

README.md
articles/monorepo.md
articles/reduce-heroku-slug-size.md
articles/schedule-netlify-builds-with-github-actions.md

Some copy text felt off.
Some is now unnecessary.

articles: clean up old Heroku slug article

---

theme/article.html
theme/index.html

Better use CSS variables for clarity.

theme: more light/dark theme adjustments

---

config.json
theme/index.html

The collection wasn't feeling quite right.
This is getting closer.

config.json: re-tag all articles

---

theme/index.html

Keep it simple.
Make it more memorable.
Show more content on mobile.

Shorten description

---

go.mod
go.sum
main.go
theme/article.html
theme/index.html

By request from a friend.
Also, analytics say 3,872 404s to this endpoint in May.

main.go: add JSON feed

---

README.md
config.json
main.go

Now that I'm publishing a JSON feed again,
use a Published date to avoid re-publishing updated articles.

main.go: add published date

---

main.go

main.go: fix logo in RSS feed

---

README.md

I'm switching to `main` from `master` for this repo.

README.md: update Netlify config

---

articles/update-a-github-fork.md

I try to keep `main` untouched, always work in a branch.

articles/update-a-github-fork: remove conflicts

---

config.json

I've been tweaking this version.

config.json: remove canonical for Monorepo

---

config.json

config.json: copy edit article descriptions

---

code/cache-api-requests/main.rb

This would be a good technique to describe in another article.

code/cache-api-requests: run if current file

---

README.md
config.json
main.go

My JSON linter is complaining about the JSON file not being an object
as its outer structure. I can kind of dig that, don't mind changing.

config.json: use an outer object

---

README.md
config.json
main.go

This reverts commit 0a79984d3e241b0ca8606c69fead03b5ac2bd9ea.
That change broke `blog add`.
Instead, I'm going to stop using coc-json.
https://github.com/croaky/laptop/pull/125

config.json: revert "use an outer object"

---

articles/heroku-postgres-read-replica-with-rails.md
config.json

Extracted from https://github.com/croaky/multi-db

articles/heroku-postgres-read-replica-with-rails: add

---

articles/heroku-postgres-read-replica-with-rails.md

19 dynos! Reference Heroku Autoscaling.

articles/read-replica: fix connections calculation

---

theme/article.html
theme/index.html

I evaluated Substack, Tinyletter, and a DIY setup with Postmark.
I think Substack is going to the cheapest and lowest maintenance,
with flexibility to change later if needed.

theme: add link to Substack newsletter

---

theme/article.html
theme/index.html

Use a gradient for article title.

theme: make dark theme more colorful

---

theme/article.html
theme/index.html

I'm digging Railway too much right now.
https://railway.app/
I want to live in the dark theme for a bit.

theme: dark theme all the time

---

articles/block-etc-hosts.md

It has moved.
https://github.com/croaky/laptop/commit/06afb8bb466c3d58f323c9a54204defd200ac689

articles/block-etc-hosts: update URL

---

code/heroku-to-slack.rb

Use `Hash#dig`.
https://devcenter.heroku.com/articles/webhook-events#api-collaborator

code/heroku-to-slack: support collaborator webhooks

---

.github/workflows/deno.yml
.github/workflows/deno_deploy.yml

As seen in https://deno.com/blog/hugo-blog-with-deno-deploy

.github/workflows/deno_deploy: add

---

README.md
articles/align-markdown-tables-in-vim.md
articles/heroku-slack-aws-lambda.md
articles/north-star-metric.md
articles/postgres-visualize-slow-queries.md
articles/pull-requests-and-kanban.md
articles/retention-curves-mixpanel-google-sheets.md
articles/search-projects-in-vim.md
articles/spell-check-in-vim.md
config.json
main.go
theme/article.html
theme/index.html
theme/public/_headers

Remove redirects and headers, which is a little unfortunate.

all: fix for Deno Deploy

---

code/heroku/db-restore-dev-from-downloaded-backup
config.json

Heroku Postgres databases add the `pg_stat_statements` extension
within the `heroku_ext` schema.

code/heroku: create prerequisites

---

articles/create-postgres-indexes-concurrently.md
articles/dns-cdn-origin.md
articles/find-and-replace.md
articles/fly-io-multi-region-postgres-read-replicas.md
articles/four-phase-test.md
articles/heroku-dataclips-clone.md
articles/heroku-postgres-read-replica-with-rails.md
articles/kill-pid.md
articles/postgres-concat-ws.md
articles/postgres-debug-slow-queries.md
articles/postgres-download-restore.md
articles/restricted-postgres-access-render-crunchy.md
articles/retention-curves-google-sheets.md
articles/ruby-postgres-job-queue.md
articles/ruby-script-file-guard.md
articles/run-tests-in-vim.md
articles/search-projects-in-vim.md
articles/ssh-ed25519.md
articles/test-mock-vs-stub-vs-spy.md
articles/thin-api-clients.md

Better match index with article pages.

style: use less uppercase

---

README.md
articles/philosophy-of-software-design.md
theme/index.html

Move over from https://github.com/croaky/learn/tree/main/philosophy-of-software-design#modules-should-be-deep
and cut it down a little.

articles/philosophy-of-software-design: add

---

main.go
main_test.go

main: fix embed

---

articles/postgres-tips.md
code/postgres/db-download-prod.sh
code/postgres/db-restore-dev.sh

This will enable syntax highlighting in the resulting article.

code: add file extension to shell scripts

---

code/postgres/db-restore-dev.sh

In Vim via Treesitter, this gives me syntax highlighting.

code/postgres: use SQL heredocs

---

articles/monorepo.md

articles/monorepo: fix broken Markdown link

---

main.go

- Add HTTP status codes (200, 404) to all log entries for clarity
- Handle .well-known directory requests with immediate 404 response
- Suppress "Article not found" messages for non-article paths
- Change log format from "[duration] [method] [path]" to "[duration] [status] [method] [path]"
This prevents noise in logs from browser requests to .well-known paths
and makes it easier to identify successful vs failed requests at a glance.

blog: improve logging and handle .well-known requests

---

.gitignore
README.md
articles/cmd/blog.md
theme/css/site.css

Add logging, git integration, concurrent build, auto-clean,
and auto heading IDs.

articles/cmd/blog: improve
